apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: default
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: spring-petclinic
        image: 538747156150.dkr.ecr.ap-south-2.amazonaws.com/spring-petclinic:38
        ports:
        - containerPort: 8080
