apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
